### ISSUE TITLE
run docker command on install

### ISSUE THREAD

**Issue by harcesz** [YunoHost-Apps/homarr_ynh#16]
To recognise docker apps homarr is meant to run a command on first run; https://homarr.dev/docs/integrations/#docker

`-v /var/run/docker.sock:/var/run/docker.sock`

It's unclear how to run it after installing with ynh.

**Comment by tituspijean** [comment]
This is not a command, it is an instruction for the host to mount the Docker socket into Homarr's container so that it can read and access other containers on the host.

Homarr for YunoHost does not rely on Docker, this is not required.
