### ISSUE TITLE
update issue

### ISSUE THREAD

**Issue by axac** [YunoHost-Apps/homarr_ynh#21]
Mon serveur YunoHost

Matériel: Freebox delta.
Version de YunoHost: 11.2.7
J’ai accès à mon serveur : Oui
Êtes-vous dans un contexte particulier ou avez-vous effectué des modifications particulières sur votre instance ? : non
L’architecture du serveur est kvm arm64

Hello, the update is not done correctly.(13.4 --> 14.2ynh1)
The log :
https://paste.yunohost.org/raw/zopudojiha

Thanks

**Comment by tituspijean** [comment]
Closing, since several versions have been released since and hopefully the issue is resolved. Feel free to reopen if needed.
