### ISSUE TITLE
New Install Issue

### ISSUE THREAD

**Issue by wiggins-philip** [YunoHost-Apps/homarr_ynh#37]
Error: "YunoHost was able to download the asset 'main' (https://github.com/ajnart/homarr/archive/refs/tags/v0.15.3.tar.gz)\
  \ for homarr, but the asset doesn't match the expected checksum. 

Full log:
[https://paste.yunohost.org/raw/juwijesuqe](https://paste.yunohost.org/raw/juwijesuqe)

**Comment by tituspijean** [comment]
The Homarr package for YunoHost was [updated](https://github.com/YunoHost-Apps/homarr_ynh/commit/790b3a28662188fb9beadc91df12f6dca4be7c50) at 03:36 GMT+2 on 2024-05-08, while the the [v0.15.3 tag](https://github.com/ajnart/homarr/releases/tag/v0.15.3) has its assets timestamp at 16:06 on the same date, while the release is timestamped at 19:39.

So it looks like there was a sneaky update of the tag after a hotfix: https://github.com/ajnart/homarr/pull/2043

I'll update the YunoHost package to fix that.

---

Please, if you post here on the forum and also in the app issues, mention it. :wink:

**Comment by manuel-rw** [comment]
Hi,
sorry for any inconvinience that this has caused.
We are not aware of how downstream repositories are consuming our updates or how "sneaky" pushes could break them.
As part of our major update to 1.0, we will strictly adhere to the conventional commit guidelines without exceptions.
This should get rid of such issues - we're currently not happy either how Homarr's tagging currently works.
We're also implementing test coverage using unit tests for 1.0 which should reduce regressions.

I want to reiterate; sorry for the trouble. I'm happy to provide assistance if you need it. Cheers 🙌

**Comment by tituspijean** [comment]
No worries, it only took me a few minutes to understand what happened, and I totally understand the desire for a "clean and neat release"; though it can cause issues, like in this instance our automated updater had ran between the initial release and the hotfix. 😅

Cheers, and thank you for your work on Homarr! ❤️

**Comment by manuel-rw** [comment]
I'm glad that you were able to fix it.
Homarr's current architecture & pipeline is not up to standards anymore - we have tousands of instances and over 7 million image downloads.
We are working hard to make 1.0 improve on every level of that.
And using conventional commits, it should also be easier for you guys to detect breaking changes.

We do not directly interact with Yuno Host, but we're aware that many are using it.
So feel free to contact us again if you need help. I notified our other contributors about this incident and we will attempt to avoid sneaky pushes.

Cheers 👋
